 mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=notepad
    ports:
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
